spring:
  flyway:
    enabled: true
#    url: 'jdbc:h2:file:~/testdb' if want to use as file (will not recreate when app restart)
    url: 'jdbc:h2:mem:testdb'
    user: sa
#    baseline-on-migrate: true
  datasource:
#    url: 'jdbc:h2:file:~/testdb'
    url: 'jdbc:h2:mem:testdb'
    driverClassName: org.h2.Driver
    username: sa
    password:
      #jpa.hibernate.ddl-auto will persists the insert script that managed by flyway
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: DEBUG
    org:
      hibernate:
        SQL: DEBUG
